name: RSS Feed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://ramonh.dev/feed.xml"
          max_post_count: 3

