name: RSS Feed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://ramonh.dev/feed.xml
          readme-section: feed
          max: 3

